# Generated by Django 3.1.7 on 2021-03-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('ip_type', models.CharField(max_length=4)),
                ('continent_code', models.CharField(max_length=2)),
                ('continent_name', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=255)),
                ('region_code', models.CharField(max_length=2)),
                ('region_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip_code', models.CharField(max_length=25)),
                ('latitude', models.FloatField(max_length=25)),
                ('longitude', models.FloatField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Casino',
        ),
    ]
