# Generated by Django 3.1.7 on 2021-03-17 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_auto_20210306_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geomodel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='continent_code',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='continent_name',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='country_code',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='country_name',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='ip_type',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='region_code',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='geomodel',
            name='zip_code',
        ),
    ]
