# Generated by Django 3.1.7 on 2021-03-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_auto_20210318_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomodel',
            name='type',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
