# Generated by Django 3.1.7 on 2021-03-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0006_auto_20210320_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='geomodel',
            name='url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='ip',
            field=models.GenericIPAddressField(default='', null=True),
        ),
    ]
