# Generated by Django 3.1.7 on 2021-03-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_auto_20210321_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geomodel',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='continent_code',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='continent_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='country_code',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='country_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='ip',
            field=models.GenericIPAddressField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='region_code',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='region_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='type',
            field=models.CharField(blank=True, default='', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='geomodel',
            name='zip',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
